# Generated by Django 4.0.2 on 2022-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(max_length=11)),
                ('branch_vls_id', models.IntegerField(max_length=11)),
                ('exam_id', models.IntegerField(max_length=11)),
                ('class_id', models.IntegerField(max_length=11)),
                ('section_id', models.IntegerField(max_length=11)),
                ('academic_year', models.IntegerField(max_length=11)),
                ('student_id', models.IntegerField(max_length=11, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('total_subject', models.IntegerField(max_length=11)),
                ('total_mark', models.IntegerField(max_length=11)),
                ('total_obtain_mark', models.IntegerField(max_length=11)),
                ('total_grade_point', models.FloatField()),
                ('grade_id', models.IntegerField(max_length=11)),
                ('result_status', models.CharField(max_length=50)),
                ('merit_rank_in_class', models.CharField(max_length=50)),
                ('merit_rank_in_section', models.CharField(max_length=50)),
                ('remark', models.IntegerField(blank=True, max_length=11, null=True)),
                ('status', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(max_length=50)),
            ],
        ),
    ]
