# Generated by Django 4.0.2 on 2022-02-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
