# Generated by Django 4.0.2 on 2022-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_student_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch_vls_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='remark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='section_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_obtain_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_subject',
            field=models.IntegerField(),
        ),
    ]
